language: python

python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "nightly"
  - "pypy"
#  - "pypy3"

# command to install dependencies
install:
   - "pip --quiet install virtualenv"

# command to run tests
script:
  - "make test"

notifications:
  email: false
